[package]
name = "libcodejam"
version = "0.1.0"
authors = ["Nathan West <Lucretiel@gmail.com>"]
edition = "2018"

[dependencies]
derive_more = "0.11.0"
crossbeam = "0.4.1"

[[bin]]
name = "balls"
path = "src/main.rs"
